config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/about', to: 'pages#about', as: 'about'

  get '/reels', to: 'pages#reels', as: 'reels'

  resources :events, only: [:show]

  resources :pieces, only: [:show]



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :pieces, dependent: :destroy
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :pieces, dependent: :destroy
end

app/models/piece.rb
class Piece < ApplicationRecord
  belongs_to :artist
  belongs_to :event
  has_one_attached :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def show
    @event = Event.find(params[:id])
    @pieces = Piece.where(event_id: @event)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @disable_footer = true
  end

  def reels
  end
end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  def show
    @piece = Piece.find(params[:id])
  end

  # commenting below to remove any user from adding pieces
  # to use again add routes back in for new and create
  # def new
  #   @piece = Piece.new
  # end

  # def create
  #   @piece = Piece.new(piece_params)

  #   if @piece.save
  #     redirect_to piece_path(@piece)
  #   else
  #     render :new
  #   end
  # end

  private

  def piece_params
    params.require(:piece).permit(:title, :description, :artist_id, :event_id, :picture)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/show.html.erb
<%= render 'shared/navbar' %>

<div class="container-whole">

  <div class="event_header">
    <div class="event_header_text" id="<%= 'event_header_cp3' if @event.id == 3 %>">
      <%= render "shared/event_headers" %>
    </div>
    <div class="event_title">
      <h3><a href="#"><%= @event.title %></a></h3>
    </div>
  </div>


  <div class="gallery">
      <% if @event.id == 4 %>
          <% @pieces.each do |piece| %>
            <div class="gallery-column">
              <div class="piece piece3">
                  <%= link_to piece_path(piece) do %>
                  <%= cl_image_tag piece.picture.key %>
                  <% end %>
              </div>
            </div>
          <% end %>
      <% elsif @event.id == 3 %>
        <%= render "shared/cp3" %>
      <% else %>
        <% @pieces.each do |piece| %>
          <div class="gallery-column">
            <div class="piece piece2">
                <%= cl_image_tag piece.picture.key %>
            </div>
          </div>
        <% end %>
      <% end %>
      <!-- assembled pieces -->
      <br>
      <% unless @event.id == 3 %>
      <h2 id="gallery-separator">Certain individual cardboard response pieces in the images above were assembled into the sculptures seen below at the Cardboard Project 1.0 and 2.0 events.</h2>
      <% end %>



      <% if @event.id == 2 %>
      <!--   <div class="gallery-column">
          <div class="piece">
            <#%= cl_image_tag ("https://res.cloudinary.com/jordannadroj/image/upload/v1618347749/cp2assembled1_ihsxwf.png") %>
          </div>
        </div> -->
        <div class="gallery-column">
          <div class="piece">
            <%= cl_image_tag ("https://res.cloudinary.com/jordannadroj/image/upload/v1618348050/Screenshot_2021-04-12_131143_jcyihc.png") %>
          </div>
        </div>
        <div class="gallery-column">
          <div class="piece">
            <%= cl_image_tag ("https://res.cloudinary.com/jordannadroj/image/upload/v1618348051/Screenshot_2021-04-12_131359_utcifm.png") %>
          </div>
        </div>
        <div class="gallery-column">
          <div class="piece">
            <%= cl_image_tag ("https://res.cloudinary.com/jordannadroj/image/upload/v1618348051/Screenshot_2021-04-12_131557_cezga4.png") %>
          </div>
        </div>
        <% elsif @event.id == 1 %>
          <div class="gallery-column">
            <div class="piece">
              <%= image_tag "piece1.jpeg", alt: "piece1" %>
            </div>
          </div>
          <div class="gallery-column">
            <div class="piece">
              <%= image_tag "piece2.jpeg", alt: "piece2" %>
            </div>
          </div>
      <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cardboard Project</title>
    <%= favicon_link_tag asset_path('logo-fav.png') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>



    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
    <%= render 'shared/footer' unless @disable_footer %>
  </body>
</html>

app/views/pages/about.html.erb
<%= render 'shared/navbar' %>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path "https://res.cloudinary.com/jordannadroj/image/upload/v1618347749/cp2assembled1_ihsxwf.png", alt: "alttext" %>);">
  <div class="container">
    <h1>The Cardboard Project</h1>
    <br>
    <p>Cardboard Project event’s feature cardboard and cardboard responses in an artistically creative way and in order to spread important messages.</p>

    <p>The Cardboard Project is a unique event that was inspired by the culture of individuals experiencing homelessness and poverty, who often write messages and stories on pieces of cardboard. The Cardboard Project features a unique artwork, created using messages written on cardboard. These messages respond to a different question every year, focusing on human connection, recovery, wisdom, community, listening, spirituality, and other themes. The Cardboard Project also features talks by thought leaders, discussions with our members, experiences inviting us all to connect, and an exhibition of our members’ artistic creations. The overall goal of the Cardboard Project is to dismantle prevailing negative stigmas and strive towards a Downtown Eastside neighbourhood where members are seen, heard, and validated, while feeling connected to the greater community.</p>
  </div>
</div>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path "background3.jpeg", alt: "alttext" %>);">
  <div class="container">
    <h1 style="text-align: right">The Story Behind It</h1>
    <br>
    <p>“We often see people in the Downtown Eastside sitting on the sidewalk holding cardboard with a plea on it. Some examples that I'm sure you can relate to include: "Spare change please" or "Need Food" or even for those who get creative, "Smile if you masturbate". Although this showed me what the person's NEEDS were, I realized it wasn't reflective of what the person's story was. To find out, I decided -- why not ask a question that helped me learn about who a person was rather than their needs only? </p>

    <p>To find out, my team and I cut out 100+ cardboard pieces and began asking people to share something in their past that's changed who they are today. Some responses are uplifting and/or heartbreaking. Most importantly, these responses challenge us to see the Downtown Eastside community through a different lens. As a lover of tile art (I already had a giraffe in tile art in my room) and the cardboard responses, I decided to fuse both use the cardboard pieces to form the shape of three eyes. This will be featured on 10ft tall bamboo sticks designed by Marcel Mousseau (artist of the DTES)” <em>- Christina Wong, Executive Director of Employ to Empower</em></p>
  </div>
</div>

<!-- <div class="container" id="sponsors"> -->
<!-- </div> -->

app/views/pages/home.html.erb
<div style="padding: 0; height: 100vh;" class="banner">
  <%= cl_video_tag ("https://res.cloudinary.com/jordannadroj/video/upload/v1618952340/cardboard/CP_q8qisa.mp4"), class: "home_video", autoplay: :autoplay, loop: :loop, muted: :muted, playsinline: :playsinline%>
  <!-- video -->
  <!-- <h1 id="title"></h1> -->
  <div class="home-text">
    <h1 id="homepage_question"><span id="banner-typed-text"></span></h1>
    <%= link_to event_path(3), id: "view" do %>
      <p style="font-size: 30px;"><em>The Cardboard Project 3.0 &rarr;</em></p>
    <% end %>
  </div>
</div>

app/views/pages/reels.html.erb
<%= render 'shared/navbar' %>


<div class="banner-reels">
  <a href="/events/3" id="back-arrow-link">
    <p id="back-arrow-reels">&larr; Cardboard Project 3.0</p>
  </a>
  <div class="container" style="margin-top: 60px;">
    <h1>Employ to Empower Entrepreneur CP 3.0 Video Responses</h1>
    <hr>
    <p class="reels_p">Residents in the Downtown Eastside who complete Employ to Empower's (ETE) Development program have the opportunity to join the Entrepreneurship program. Entrepreneurs in the program are supported by business professionals through personalized weekly mentorship sessions and have access to affordable microloans. ETE's goal is for our entrepreneurs to have a long-term sustainable economic effect on our members.</p>
    <br>
    <p class="reels_p">This year, we dove deeper into some of ETE's entrepreneurs' experiences in line with Cardboard Project 3.0's theme of Connection in Social Isolation."</p>
  </div>
</div>


<div class="banner" id="j_a" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path "cp3/IMG_9389.jpg", alt: "alttext" %>);">
  <a href="/events/3" class="back-arrow-videos">
    <p class="back-arrow-videos">&larr; Cardboard Project 3.0</p>
  </a>
  <div class="container video-container">
    <iframe type="text/html" class="responsive-iframe" width="720" height="405" src="https://www.youtube.com/embed/mU1TN0jMi70?cc_load_policy=1&cc_lang_pref=en" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </div>
</div>

<div class="banner" id="minah" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path "cp3/IMG_6772.jpg", alt: "alttext" %>);">
  <a href="/events/3" class="back-arrow-videos">
    <p class="back-arrow-videos">&larr; Cardboard Project 3.0</p>
  </a>
  <div class="container video-container">
    <iframe type="text/html" class="responsive-iframe" width="720" height="405" src="https://www.youtube.com/embed/eC4F8hoozME?cc_load_policy=1&cc_lang_pref=en" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </div>
</div>

<div class="banner" id="m_e" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path "cp3/elwood.jpg", alt: "alttext" %>);">
  <a href="/events/3" class="back-arrow-videos">
    <p class="back-arrow-videos">&larr; Cardboard Project 3.0</p>
  </a>
  <div class="container video-container">
    <iframe type="text/html" class="responsive-iframe" width="720" height="405" src="https://www.youtube.com/embed/YHxc46RoD9g?cc_load_policy=1&cc_lang_pref=en" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </div>
</div>

<div class="banner" id="iven" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path "cp3/connection.jpg", alt: "alttext" %>);">
  <a href="/events/3" class="back-arrow-videos">
    <p class="back-arrow-videos">&larr; Cardboard Project 3.0</p>
  </a>
  <div class="container video-container">
    <iframe type="text/html" class="responsive-iframe" width="720" height="405" src="https://www.youtube.com/embed/LDjH8zUV7Ls?cc_load_policy=1&cc_lang_pref=en" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </div>
</div>

app/views/pieces/new.html.erb
<%= render 'shared/navbar' %>

<div class="container">
  <%= simple_form_for([@event, @piece]) do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :artist_id, collection: Artist.all %>
    <%= f.input :event_id, collection: Event.all %>
    <%= f.input :picture, as: :file %>
    <%= f.submit "Add Piece", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/pieces/show.html.erb
<%= render 'shared/navbar' %>

<div class="container-show">
  <br>
  <a href="/events/3" id="back-arrow-link">
    <p id="back-arrow">&larr;</p>
  </a>
  <br>
  <h1><%= @piece.title %> <span style="color: #d13b2c;"> | </span> <span style="font-weight: 200;"><%= @piece.artist.name %></span></h1>
  <br>
  <br>
  <br>
  <div class="row">
    <div class="col-xl-8">
      <div>
        <%= cl_image_tag @piece.picture.key, class: "show-photo" %>
      </div>
    </div>
    <div class="col-xl-4">
      <%#= @piece.description %>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam laboriosam repellendus esse perspiciatis assumenda fugit eaque cupiditate ut asperiores obcaecati dolorum, ex in molestiae explicabo, ea soluta! Blanditiis, recusandae, fuga!</p>
      <br>
      <h3>Location</h3>
      <p>Vancouver</p>
      <br>
      <h3>Materials</h3>
      <p>cardboard</p>
    </div>
  </div>
</div>

app/views/shared/_cp3.html.erb
<div class="gallery-column">
  <div class="piece piece3">
    <a href="../reels.html#j_a">
      <%= image_tag "cp3/IMG_9389.jpg", alt: "alttext" %>
    </a>
    <div class="link_to_video_div">
      <a class="link_to_video" href="../reels#j_a">See Jeanette & Alley's Story</a>
    </div>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece3">
    <a href="../reels.html#j&a">
      <%= image_tag "cp3/IMG_9390.jpg", alt: "alttext" %>
    </a>
    <div class="link_to_video_div">
      <a class="link_to_video" href="../reels.html#j_a">See Jeanette & Alley's Story</a>
    </div>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece3">
    <a href="../reels.html#minah">
      <%= image_tag "cp3/IMG_6772.jpg", alt: "alttext" %>
    </a>
    <div class="link_to_video_div">
      <a class="link_to_video" href="../reels.html#minah">See Minah's Story</a>
    </div>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece3">
    <a href="../reels.html#m_e">
      <%= image_tag "cp3/mark.jpg", alt: "alttext" %>
    </a>
    <div class="link_to_video_div">
      <a class="link_to_video" href="../reels.html#m_e">See Mark & Elwood's Story</a>
    </div>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece3">
    <a href="../reels.html#m_e">
      <%= image_tag "cp3/elwood.jpg", alt: "alttext" %>
    </a>
    <div class="link_to_video_div">
      <a class="link_to_video" href="../reels.html#m_e">See Mark & Elwood's Story</a>
    </div>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece3">
    <a href="../reels.html#iven">
      <%= image_tag "cp3/connection.jpeg", alt: "alttext" %>
    </a>
    <div class="link_to_video_div">
      <a class="link_to_video" href="../reels.html#iven">See Iven's Story</a>
    </div>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9342.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9344.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9345.jpg", alt: "alttext" %>
  </div>
</div>

<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9346.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9347.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9348.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9349.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9350.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9351.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9353.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9354.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9355.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9356.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9357.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9358.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9359.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9360.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9361.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9362.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9364.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9365.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9366.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9367.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9368.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9369.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9370.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9371.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9372.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9373.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9374.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9375.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9376.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9377.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9378.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9379.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9380.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9381.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9382.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9383.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9384.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9385.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9386.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9387.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9388.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9391.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9392.jpg", alt: "alttext" %>
  </div>
</div>
<div class="gallery-column">
  <div class="piece piece2">
      <%= image_tag "cp3/IMG_9393.jpg", alt: "alttext" %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-container">
    <div class="footer">
      <div class="footer-logo">
        <!-- uncomment out to reveal ETE logo -->
        <%= image_tag "Logo-ETE-White-2019.png", alt: "alttext", id: "footer-logo-image" %>
        <div class="text-and-sponsors">
          <p id="presented-by">The Cardboard Project is presented by Employ to Empower</p>
          <div class="sponsors">
            <a target="_blank" href="https://dailyhive.com/">
              <%= image_tag "sponsors/dailyhive.svg", alt: "alttext" %>
            </a>
            <a target="_blank" href="https://www.bchousing.org/home">
              <%= image_tag "sponsors/bchousing.png", alt: "alttext" %>
            </a>
            <a target="_blank" href="https://www.sfu.ca/vpexternal/vice-president-external-relations.html">
              <%= image_tag "sponsors/externalrelations.jpeg", alt: "alttext" %>
            </a>
          </div>
        </div>

      </div>
      <div class="footer-lists">
        <div class="footer-links">
          <ul>
            <li><a target="_blank" href="https://employtoempower.com/">Employ to Empower</a></li>
            <li><a target="_blank" href="https://employtoempower.com/about-us/">About Us</a></li>
            <li><a target="_blank" href="https://employtoempower.com/corporate-social-responsibility/">Corporate Programs</a></li>
            <li><a target="_blank" href="https://employtoempower.com/get-involved/">Get Involved</a></li>
          </ul>
        </div>
        <div class="footer-links">
          <ul>
            <li><a target="_blank" href="https://employtoempower.com/contact-us/">Contact Us</a></li>
            <li><a target="_blank" href="https://employtoempower.com/development/">Development Program</a></li>
            <li><a target="_blank" href="https://employtoempower.com/advocacy/">Advocacy Division</a></li>
            <li><a target="_blank" href="https://employtoempower.com/entrepreneurship/">Entrepreneurship Program</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-bottom">
      <a target="_blank" id="jordan-tag" href="https://github.com/jordannadroj">Designed and developed by Jordan Siemens</a>
      <div class="social">
        <ul>
          <li><a target="_blank" href="https://www.facebook.com/employtoempower/"><i class="fab fa-facebook-f"></i></a></li>
          <li><a target="_blank" href="https://www.linkedin.com/company/employ-to-empower/"><i class="fab fa-linkedin-in"></i></a></li>
          <li><a target="_blank" href="https://www.instagram.com/employtoempower/"><i class="fab fa-instagram"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand navbar-light  justify-content-between">
    <%= link_to root_path, class: "navbar-brand" do  %>
      <img src="https://res.cloudinary.com/jordannadroj/image/upload/c_thumb,w_200,g_face/v1618649254/cardboard/Logo-ETE-Written_1_lhg56k.png" alt="Employ to Empower" class="desktop">
      <img src="https://res.cloudinary.com/jordannadroj/image/upload/c_thumb,w_200,g_face/v1618649826/cardboard/Logo-ETE-Black-HalfSize-2019_b9qsaw.png" alt="Employ to Empower" class="mobile">
    <% end %>
    <!-- <li class="nav-item <#%= 'active' if current_page?(about_path)%>"> -->
          <!-- </li> -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav navbar-nav navbar-center mr-auto mt-2 mt-lg-0">
          <li class="nav-item <%= 'active' if current_page?(event_path(3))%>">
            <a class="nav-link" href="/events/3">CP 3.0</a>
          </li>
          <li class="nav-item <%= 'active' if current_page?(reels_path)%>">
            <a class="nav-link" href="/reels">CP 3.0 Videos</a>
          </li>
          <li class="nav-item <%= 'active' if current_page?(event_path(2))%>">
            <a class="nav-link" href="/events/2">CP 2.0</span></a>
          </li>
          <li class="nav-item <%= 'active' if current_page?(event_path(1))%>">
            <a class="nav-link" href="/events/1">CP 1.0</a>
          </li>
          <li class="nav-item mobile <%= 'active' if current_page?(event_path(1))%>">
            <a class="nav-link <%= 'active' if current_page?(about_path)%>" href="/about">Our Story</a>
          </li>
        </ul>
      <div class="nav nav-item navbar-nav ml-auto desktop" id="about-link">
        <a class="nav-link <%= 'active' if current_page?(about_path)%>" href="/about">Our Story</a>
      </div>
    </div>
</nav>